# Current Date and Time (UTC): 2025-06-13 13:09:40
# Current User's Login: Khoasoma
# Config version. Do not change this
config-version = "2.7"

#=============================================================================#
# Core Server Settings
#=============================================================================#
bind = "0.0.0.0:25565"
motd = "<#09add3>A Velocity Server"
show-max-players = 500

#=============================================================================#
# Security & Authentication
#=============================================================================#
online-mode = true
force-key-authentication = true
prevent-client-proxy-connections = false

# IP Forwarding Settings
player-info-forwarding-mode = "NONE"  # NONE, LEGACY, BUNGEEGUARD, MODERN
forwarding-secret-file = "forwarding.secret"

# Anti-DDoS Protection
[antiddos]
enabled = true
# Connection Controls
max-connections-per-second = 1000
connection-threshold = 100
connection-throttle = 3000
timeout = 5000

# IP-based Protection
blacklist-duration = 3600  # seconds
auto-blacklist = true
whitelist-ips = [
    "127.0.0.1",
    "::1"
]

# Layer 7 Protection
http-flood-threshold = 500
request-rate-limit = 200
max-concurrent-connections = 1000

# Anti-Bot Protection
[antibot]
enabled = true
attack-mode = "AUTO"  # OFF, AUTO, ALWAYS
verification-timeout = 30

# Connection Patterns
max-joins-per-second = 3
max-accounts-per-ip = 3
min-connection-delay = 100

# Bot Detection
username-validation = true
username-regex = "^[a-zA-Z0-9_]{3,16}$"
blocked-usernames = [
    "^Bot\\d+$",
    "^User\\d+$",
    "^Player\\d+$"
]

#=============================================================================#
# Network & Protocol
#=============================================================================#
[network]
# TCP Settings
tcp-fast-open = false
tcp-nodelay = true
enable-reuse-port = false

# Compression
compression-threshold = 256
compression-level = -1

# Timeouts
connection-timeout = 5000
read-timeout = 30000
login-timeout = 30000

# Protocol Settings
validate-packets = true
max-packet-size = 2097152  # 2MB
allowed-protocols = [
    762,  # 1.20.2
    761,  # 1.20.1
    760   # 1.19.4
]

#=============================================================================#
# Server Configuration
#=============================================================================#
[servers]
# Server Definitions
lobby = "127.0.0.1:30066"
factions = "127.0.0.1:30067"
minigames = "127.0.0.1:30068"

# Try Order
try = [
    "lobby"
]

#=============================================================================#
# Forced Hosts
#=============================================================================#
[forced-hosts]
"lobby.example.com" = ["lobby"]
"factions.example.com" = ["factions"]
"minigames.example.com" = ["minigames"]

#=============================================================================#
# Packet Protection
#=============================================================================#
[packet]
# Packet Filtering
max-packet-size = 2097152  # 2MB
check-nbt = true

# Blocked Packets
blocked-packets = [
    "MC|BEdit",
    "MC|BSign",
    "MC|ItemName",
    "WECUI",
    "WDL|INIT",
    "WDL|CONTROL",
    "FML|HS",
    "FML|MP",
    "REGISTER"
]

# NBT Protection
nbt-max-depth = 16 # Default is 16
nbt-max-size = 1048576  # 1MB

# Rate Limiting
packet-rate-limit = 1000
packet-burst-limit = 100

#=============================================================================#
# Rate Limits
#=============================================================================#
[limits]
# Command Rate Limits
command-rate-limit = 50
forward-commands-if-rate-limited = true
kick-after-rate-limited-commands = 0

# Tab Complete Rate Limits
tab-complete-rate-limit = 10
kick-after-rate-limited-tab-completes = 0

# Chat Rate Limits
chat-rate-limit = 20
chat-burst-limit = 5

#=============================================================================#
# Performance & Optimization
#=============================================================================#
[performance]
# Threading
network-threads = 4
compression-threads = 2
async-tasks-threads = 4

# Memory
direct-buffer-size = 64  # MB
heap-warning-threshold = 85  # percent

# Queue Settings
queue-capacity = 1000
max-pending-connections = 500

#=============================================================================#
# Monitoring & Metrics
#=============================================================================#
[monitoring]
# Metrics Collection
enabled = true
collection-interval = 60  # seconds
detailed-metrics = false

# Performance Monitoring
monitor-tps = false
monitor-memory = true
monitor-connections = true

# Alerting
alert-threshold-tps = 15.0
alert-threshold-memory = 85
alert-threshold-connections = 1000

#=============================================================================#
# Plugin & Mod Support
#=============================================================================#
[plugins]
announce-forge = false
bungee-plugin-message-channel = true
announce-proxy-commands = true

#=============================================================================#
# Query Settings
#=============================================================================#
[query]
enabled = false
port = 25565
map = "Velocity"
show-plugins = false

#=============================================================================#
# Logging & Debug
#=============================================================================#
[logging]
# Connection Logging
log-player-connections = true
enable-player-address-logging = true
log-command-executions = false

# Debug Options
debug-logging = false
packet-logging = false
verbose-logging = false

# File Options
log-rotation = true
log-retention-days = 7
save-thread-dumps = false

#=============================================================================#
# Advanced Features
#=============================================================================#
[advanced]
# Connection Handling
kick-existing-players = false
failover-on-unexpected-server-disconnect = true
accepts-transfers = false

# Ping Settings
ping-passthrough = "DISABLED"  # DISABLED, MODS, DESCRIPTION, ALL
sample-players-in-ping = false

# Proxy Protocol
haproxy-protocol = false
proxy-protocol-ports = [25565]

#=============================================================================#
# Cleanup & Maintenance
#=============================================================================#
[maintenance]
# Auto Cleanup
enable-auto-cleanup = true
cleanup-interval = 300  # seconds

# Data Retention
connection-history = 3600  # seconds
metrics-retention = 86400  # seconds
temporary-data-ttl = 300  # seconds

#=============================================================================#
# API Configuration
#=============================================================================#
[api]
enabled = false
port = 8080
bind-address = "127.0.0.1"

# Security
api-token = ""
allowed-origins = ["*"]
rate-limit = 60  # requests per minute

# Endpoints
enable-metrics-endpoint = true
enable-players-endpoint = true
enable-servers-endpoint = true