name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev/3.0.0" ]
  pull_request:
    branches: [ "main", "dev/3.0.0" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.11.1
    
    - name: Add execution permission to gradlew
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test
    
    - name: Archive build results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-results
        path: build/reports/

    - name: Update Build Constants
      run: |
        echo "package com.velocitypowered.proxy;
        
        public final class BuildConstants {
            public static final String VERSION = \"3.0.0\";
            public static final String BUILD_TIME = \"$(date -u +%Y-%m-%d\\ %H:%M:%S)\";
            public static final String USER = \"${{ github.actor }}\";
            
            private BuildConstants() {
                // Prevent instantiation
            }
        }" > proxy/src/main/java/com/velocitypowered/proxy/BuildConstants.java

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
